// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-c5i_tPMli9LzkzyYloo61ZZk8CzgpM8',
    appId: '1:1064693740217:web:7d92524fd5dcf8aa666168',
    messagingSenderId: '1064693740217',
    projectId: 'admivida-app',
    authDomain: 'admivida-app.firebaseapp.com',
    storageBucket: 'admivida-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLRGwpNIUEjZwR2Li4cBe54YgTx4XPZA',
    appId: '1:1064693740217:android:d6aee39a72bd6da2666168',
    messagingSenderId: '1064693740217',
    projectId: 'admivida-app',
    storageBucket: 'admivida-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMIsrEbde2hq_FolHUuNCtLM-lDTnJHc',
    appId: '1:1064693740217:ios:400297cd35499a5c666168',
    messagingSenderId: '1064693740217',
    projectId: 'admivida-app',
    storageBucket: 'admivida-app.firebasestorage.app',
    iosBundleId: 'com.pacosotelo.admivida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmMIsrEbde2hq_FolHUuNCtLM-lDTnJHc',
    appId: '1:1064693740217:ios:400297cd35499a5c666168',
    messagingSenderId: '1064693740217',
    projectId: 'admivida-app',
    storageBucket: 'admivida-app.firebasestorage.app',
    iosBundleId: 'com.pacosotelo.admivida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-c5i_tPMli9LzkzyYloo61ZZk8CzgpM8',
    appId: '1:1064693740217:web:4b9a5a5aa7cef465666168',
    messagingSenderId: '1064693740217',
    projectId: 'admivida-app',
    authDomain: 'admivida-app.firebaseapp.com',
    storageBucket: 'admivida-app.firebasestorage.app',
  );
}
